from __future__ import annotations

from ..core import *


KEY_TABLE_SUBDIRS = {
    "analysis_data_provenance": "provenance",
    "imputation_diagnostics_summary": "provenance",
    "benchmark_agent_model_scores": "leaderboards",
    "benchmark_scores_long": "leaderboards",
    "benchmark_mini_leaderboards": "leaderboards",
    "task_benchmark_reliable_summary": "task_level",
    "task_to_benchmark_alignment": "task_level",
    "task_within_benchmark_similarity": "task_level",
    "task_cross_benchmark_similarity": "task_level",
    "task_representative_tasks": "task_level",
    "task_predictability_ranked": "task_level",
    "harbormix_selected_tasks": "harbormix",
    "harbormix_selection_by_benchmark": "harbormix",
    "terminus_delta_by_model": "benchmark_level",
}


def key_table_path(name: str) -> Path:
    subdir = KEY_TABLE_SUBDIRS.get(name, "benchmark_level" if name.startswith("benchmark") else "task_level")
    return KEY_TABLE_DIR / subdir / f"{name}.csv"


def write_key_analysis_reports(
    study_tables: dict[str, pd.DataFrame],
    benchmark_result: ImputationResult,
    task_result: ImputationResult,
    included_benchmarks: list[str],
    mini_leaderboard_figures: list[str],
) -> None:
    filter_table = study_tables["benchmark_filtering"]
    provenance = study_tables["analysis_data_provenance"]
    imputation_diagnostics = study_tables["imputation_diagnostics_summary"]
    agent_model_scores = study_tables["benchmark_agent_model_scores"]
    model_effects = study_tables["benchmark_model_adjusted_effects"]
    agent_effects = study_tables["benchmark_agent_adjusted_effects"]
    variance_filtered = study_tables["benchmark_variance_decomposition_filtered"]
    benchmark_role = study_tables["benchmark_model_agent_role_by_benchmark"]
    benchmark_clusters = study_tables["benchmark_similarity_clusters"]
    redundancy = study_tables["benchmark_redundancy_pairs_filtered"]
    uniqueness = study_tables["benchmark_uniqueness_filtered"]
    agent_lift = study_tables["benchmark_agent_lift_vs_terminus"]
    terminus_by_model = study_tables["terminus_delta_by_model"]
    task_summary = study_tables["task_benchmark_reliable_summary"]
    alignment = study_tables["task_to_benchmark_alignment"]
    task_similarity = study_tables["task_within_benchmark_similarity"]
    task_cross_similarity = study_tables["task_cross_benchmark_similarity"]
    representative_tasks = study_tables["task_representative_tasks"]
    task_predictability = study_tables["task_predictability_ranked"]
    selected_tasks = study_tables["harbormix_selected_tasks"]
    selection_by_benchmark = study_tables["harbormix_selection_by_benchmark"]
    task_imputation_cv = task_result.cv.sort_values(["mae", "rmse", "rank"], na_position="last").copy()
    best_task_imputer = str(task_imputation_cv.iloc[0]["method"])
    best_task_rank = int(task_imputation_cv.iloc[0]["rank"])

    excluded = filter_table[~filter_table["include_in_key_analysis"]]
    redundant_high = redundancy[redundancy["spearman"] >= 0.75].sort_values("spearman", ascending=False)
    unique_low = uniqueness.sort_values("cv_r2_from_other_included_benchmarks")
    alignment_good = alignment[
        alignment["included_in_benchmark_level_key_filter"] & (alignment["n_reliable_bounded_tasks"] >= 3)
    ].sort_values("spearman_agent_model_correlation", ascending=False)
    task_pool = task_summary.sort_values("candidate_pool_tasks", ascending=False)
    _model_col = "model_adj_partial_r2_over_agent" if "model_adj_partial_r2_over_agent" in benchmark_role.columns else "model_partial_r2_over_agent"
    _agent_col = "agent_adj_partial_r2_over_model" if "agent_adj_partial_r2_over_model" in benchmark_role.columns else "agent_partial_r2_over_model"
    role_gap = benchmark_role.assign(
        absolute_role_gap=lambda df: (df[_model_col] - df[_agent_col]).abs()
    ).sort_values("absolute_role_gap", ascending=False)
    hard_tasks = task_predictability.sort_values("task_unpredictability_score", ascending=False)
    representative_top = representative_tasks.sort_values("useful_representativeness_score", ascending=False)
    predictable_benchmarks = uniqueness.sort_values("cv_r2_from_other_included_benchmarks", ascending=False)
    story_unique_benchmarks = ", ".join(unique_low["benchmark"].head(5).tolist())
    story_predictable_benchmarks = ", ".join(predictable_benchmarks["benchmark"].head(5).tolist())
    story_hard_tasks = ", ".join((hard_tasks["benchmark"] + "/" + hard_tasks["task_id"]).head(3).tolist())
    story_representative_tasks = ", ".join(
        (representative_top["benchmark"] + "/" + representative_top["task_id"]).head(3).tolist()
    )
    selected_tiers = selected_tasks["difficulty_tier"].value_counts().to_dict()
    selected_tier_summary = ", ".join(f"{tier}: {count}" for tier, count in selected_tiers.items())
    key_tables = sorted(str(path.relative_to(KEY_TABLE_DIR)) for path in KEY_TABLE_DIR.rglob("*.csv"))
    all_key_figures = sorted(str(path.relative_to(KEY_FIGURE_DIR)) for path in KEY_FIGURE_DIR.rglob("*.png"))
    key_figures = [name for name in all_key_figures if not name.startswith("leaderboards/per_benchmark/")]
    per_benchmark_leaderboard_count = len(all_key_figures) - len(key_figures)
    code_files = [
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'core')}/`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'preprocessing' / 'svd_imputation.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'coverage_filtering.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'intermediate_tables.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'model_agent_roles.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'benchmark_predictability.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'benchmark_similarity.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'leaderboards.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'terminus_comparison.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_alignment.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_selection.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_similarity.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'provenance.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'visualization')}/`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'reporting' / 'key_analysis_report.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'cli.py')}`",
    ]

    report_lines = [
        "# Key Analysis Cross-Benchmark Analysis",
        "",
        "This report is intended to be read directly. Figures and compact table previews are embedded inline; CSV paths are listed for exact numbers and reproducibility.",
        "",
        "## Directory Contract",
        "",
        f"- Key analysis tables: `{md_path(KEY_TABLE_DIR)}/`",
        f"- Key analysis figures: `{md_path(KEY_FIGURE_DIR)}/`",
        "- Layered table groups: `benchmark_level/`, `leaderboards/`, `task_level/`, `harbormix/`, and `provenance/`.",
        "- Layered figure groups: `benchmark_level/`, `leaderboards/`, `task_level/`, and `harbormix/`.",
        "- Leaderboard figures are further layered into `leaderboards/per_benchmark/` and `leaderboards/clustered/`; the report embeds only the clustered pages to keep reading compact.",
        f"- Intermediate study outputs: `{md_path(INTERMEDIATE_STUDY_DIR)}/`",
        f"- Intermediate imputed matrices and diagnostics: `{md_path(PROCESSED_DIR)}/`",
        "",
        "The current preprocessing contract is task-first: task scores are filled first, then benchmark scores are aggregated from the filled task matrix. The original benchmark matrix is retained as metadata and as a sanity check, but benchmark scores are not imputed directly.",
        "",
        "BenchPress mapping note: Dimitris's BenchPress repo treats benchmark prediction as an explicit analysis problem, compares benchmark-regression and SVD families under held-out validation, and uses a blend because regression can be more accurate while SVD gives broader coverage. Our schema is task-rich rather than model-benchmark-only, so we map that lesson by validating several task-fill families on held-out observed cells, using benchmark/task predictability tables for difficulty ranking, and keeping task aggregate alignment as a diagnostic rather than blindly trusting every aggregate.",
        "",
        "Data provenance for the main studies:",
        "",
        *markdown_table(provenance, ["analysis", "primary_matrix", "processed_output"], 10),
        "",
        "Preprocessing diagnostics:",
        "",
        f"Task imputation method: each score column is robustly centered and scaled after `log1p` for nonnegative unbounded columns. The pipeline compares column-median, row-mean shrinkage, two-way shrinkage, and low-rank iterative SVD candidates on held-out observed cells, then uses the lowest-MAE method. For this run the selected task imputer is `{best_task_imputer}` with rank {best_task_rank}. Observed task cells are restored exactly; filled task scores are inverse-transformed and clipped to the observed range of that task. Benchmark scores are then calculated as per-benchmark means across those task scores. Task-level imputation remains less stable than dense benchmark tables because the task matrix is much wider and sparser, so task conclusions are restricted to reliable bounded non-degenerate tasks.",
        "",
        *markdown_table(
            imputation_diagnostics,
            [
                "matrix",
                "preprocessing_method",
                "selected_imputation_method",
                "missing_fraction_before_processing",
                "selected_imputation_rank",
                "task_imputation_method_used_for_benchmark_aggregation",
                "task_imputation_rank_used_for_benchmark_aggregation",
                "holdout_cells",
                "holdout_rmse_scaled_score_space",
                "holdout_mae_scaled_score_space",
            ],
            4,
        ),
        "",
        "Held-out task imputation comparison:",
        "",
        *markdown_table(task_imputation_cv, ["method", "rank", "holdout_cells", "rmse", "mae"], 10),
        "",
        "Interpretation: the task matrix is sparse and very wide, so this is a validation-backed fill, not ground truth. The aggregate benchmark table is more stable than individual filled cells because it averages over many task columns, but sparse benchmarks should still be read with their task-cell missingness fields.",
        "",
        "Reliability conclusion: SVD is not automatically the right fill here. In this run, low-rank SVD improves RMSE because it reduces a few large scaled errors, but it loses on MAE, which is the better primary criterion for this mixed-scale sparse matrix because many robust-normalized task columns have outlier-sensitive tails. The selected column-median fill is therefore intentionally conservative: it preserves each task's observed center and avoids hallucinating row-level structure where the held-out cells do not support it.",
        "",
        "## Research Question Coverage Checklist",
        "",
        "| Question | Status | Main artifacts |",
        "| --- | --- | --- |",
        "| Agent vs model role overall and per benchmark | covered | `tables/benchmark_level/benchmark_variance_decomposition_filtered.csv`, `tables/benchmark_level/benchmark_model_agent_role_by_benchmark.csv`, `figures/benchmark_level/benchmark_model_vs_agent_role.png` |",
        "| BenchPress-style benchmark predictability and hard-to-predict benchmarks/tasks | covered | `tables/benchmark_level/benchmark_uniqueness_filtered.csv`, `tables/task_level/task_predictability_ranked.csv`, benchmark/task predictability figures |",
        "| Benchmark/task similarity and clustering | covered | `tables/benchmark_level/benchmark_similarity_clusters.csv`, `tables/task_level/task_cross_benchmark_similarity.csv`, clustered heatmaps |",
        "| Representative tasks per benchmark | covered | `tables/task_level/task_representative_tasks.csv`, `figures/task_level/task_best_representatives.png` |",
        "| Mini-leaderboards grouped by similar benchmarks | covered | `tables/leaderboards/benchmark_mini_leaderboards.csv`, `figures/leaderboards/clustered/mini_leaderboards_cluster_*.png` |",
        "| Agent harness improvements over Terminus | covered | `tables/benchmark_level/benchmark_agent_lift_vs_terminus.csv`, `tables/benchmark_level/terminus_delta_by_model.csv`, Terminus heatmaps |",
        "| Quantitative HaborMix task selection | covered | `tables/harbormix/harbormix_selected_tasks.csv`, `tables/harbormix/harbormix_selection_by_benchmark.csv`, `figures/harbormix/harbormix_selection_diagnostics.png` |",
        "",
        "## Study 1: Coverage Filtering",
        "",
        "**Method:** Benchmark-level claims use benchmark aggregates derived from the filled task matrix, but coverage filtering still uses evidence metadata: at least 15 agent+model rows need some observed task evidence for that benchmark, and the missingness fields describe coverage before task filling. This filter keeps the key analysis story from leaning too heavily on filled task values.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_filtering'))}`",
        "",
        "**Result overview and analysis:**",
        f"- Included {len(included_benchmarks)} of {len(filter_table)} benchmarks.",
        f"- Excluded sparse benchmarks: {', '.join(excluded['benchmark'].tolist())}.",
        f"- Benchmark scores are task aggregates, not direct benchmark-imputation outputs; pre-aggregation benchmark missing fraction was {benchmark_result.missing_fraction:.3f}.",
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_key_analysis", "observed_count", "missing_fraction", "task_cell_missing_fraction"], 12),
        "",
        "**Insight and findings:** Sparse columns should stay in appendix/provisional analysis until more experiments land. The main key analysis story should use the coverage-filtered benchmark set.",
        "",
        "## Study 2: Model vs Agent Roles",
        "",
        "**Method:** I fit fixed-effect regressions in two views. The overall view decomposes benchmark-relative score into model, agent, benchmark, and interaction terms. The per-benchmark view fits each benchmark separately and compares partial R2 from model after controlling for agent against partial R2 from agent after controlling for model.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_variance_decomposition_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_model_agent_role_by_benchmark'))}`",
        f"- `{md_path(key_table_path('benchmark_model_adjusted_effects'))}`",
        f"- `{md_path(key_table_path('benchmark_agent_adjusted_effects'))}`",
        "",
        report_image("benchmark_level/benchmark_variance_attribution.png", "Benchmark-level variance attribution"),
        "",
        report_image("benchmark_level/benchmark_model_vs_agent_role.png", "Per-benchmark model vs agent explanatory power"),
        "",
        report_image("benchmark_level/benchmark_model_adjusted_effects.png", "Model effects adjusted for agent and benchmark"),
        "",
        report_image("benchmark_level/benchmark_agent_adjusted_effects.png", "Agent effects adjusted for model and benchmark"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(variance_filtered, ["component", "adj_partial_r2_over_other_main_effects", "adj_r2", "permutation_p_value", "type"] if "adj_r2" in variance_filtered.columns else ["component", "partial_r2_over_other_main_effects", "r2", "type"], 7),
        "",
        "Benchmarks with the largest model-vs-agent role imbalance:",
        *markdown_table(role_gap, ["benchmark", _model_col, _agent_col, "dominant_dimension"], 10),
        "",
        "**Insight and findings:** Model identity explains much more overall variation than agent identity, but the role varies by benchmark. Agent effects are more useful as benchmark-specific harnessing effects than as a universal main effect.",
        "",
        "## Study 3: Agent+Model Leaderboards",
        "",
        "**Method:** I keep `agent+model` rankings as descriptive mini-leaderboards. Per-benchmark mini-leaderboards use benchmark scores aggregated from filled tasks on each benchmark's original metric scale. Each mini-leaderboard shows all available agent+model rows, grouped by model with colored bars for agents, so the same plot makes model differences and agent harness differences visible. The aggregate top-agent plot uses mean within-benchmark score percentile, because averaging scores across benchmarks with different scales would be misleading.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_agent_model_scores'))}`",
        f"- `{md_path(key_table_path('benchmark_scores_long'))}`",
        f"- `{md_path(key_table_path('benchmark_mini_leaderboards'))}`",
        f"- `{md_path(key_table_path('benchmark_similarity_clusters'))}`",
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'clustered' / 'mini_leaderboards_cluster_*.png')}`",
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'per_benchmark' / 'mini_leaderboard_*.png')}`",
        "",
        report_image("leaderboards/benchmark_agent_model_top_scores.png", "Top agent+model pairs on included benchmarks"),
        "",
        *[report_image(fig, f"Mini-leaderboards {fig}") for fig in mini_leaderboard_figures],
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_model_scores, ["rank", "agent_model", "mean_score_percentile_across_benchmarks", "original_benchmark_table_coverage"], 10),
        "",
        "**Insight and findings:** Benchmark scores should be read benchmark by benchmark. The percentile aggregate is a compact descriptive ranking only; it is not a causal agent claim because model and agent are entangled in the row identity.",
        "",
        "## Study 4: Benchmark Predictability and Similarity",
        "",
        "**Method:** Following the BenchPress idea, each included benchmark is predicted from the other included benchmarks using ridge regression with cross-validation over agent+model rows. Low or negative R2 means the benchmark is hard to reconstruct from the rest and likely contributes distinct information. Benchmark similarity uses same-dimensional vectors: every benchmark is represented by its score profile across the same agent+model rows, and clustering is run on `1 - |Spearman correlation|` so benchmarks with similar ranking behavior sit together even if one is directionally inverted.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_uniqueness_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_redundancy_pairs_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_correlation_clustered'))}`",
        "",
        report_image("benchmark_level/benchmark_uniqueness_vs_coverage.png", "Benchmark predictability ranking"),
        "",
        report_image("benchmark_level/benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict benchmarks:",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 10),
        "",
        "Most similar benchmark pairs:",
        *markdown_table(redundant_high, ["left", "right", "spearman"], 10),
        "",
        "**Insight and findings:** Predictable benchmarks are candidates for compression; hard-to-predict benchmarks should be preserved when the goal is behavioral breadth. Similarity clusters are also the basis for the grouped mini-leaderboards.",
        "",
        f"Paper-facing read: the least reconstructable benchmark set starts with {story_unique_benchmarks}. These are the strongest candidates to preserve when reducing the suite because other benchmark scores do not explain them well. In contrast, the most predictable benchmarks start with {story_predictable_benchmarks}; these are not useless, but they are where compression or cluster-level reporting is easiest to justify.",
        "",
        "## Study 5: Task Similarity, Predictability, and Representatives",
        "",
        "**Method:** Task-level analysis uses reliable, bounded, non-degenerate tasks only. Task similarity also uses same-dimensional vectors: every task is represented by its filled, standardized score profile across the same agent+model rows. A task is hard to predict when its maximum absolute profile correlation to peer tasks in the same benchmark is low. Representativeness is no longer pure correlation with the benchmark aggregate: I compute a leave-one-out aggregate correlation and multiply it by observed cross-agent/model variance, so redundant but low-discrimination tasks no longer dominate. Within- and cross-benchmark task similarity use median absolute task-profile correlations, with at most the most discriminative 40 tasks sampled per benchmark for cross-benchmark pair summaries. Difficulty tiers use mean task score thresholds: frontier <5%, hard 5-30%, medium 30-70%, easy 70-95%, saturated >95%.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('task_predictability_ranked'))}`",
        f"- `{md_path(key_table_path('task_representative_tasks'))}`",
        f"- `{md_path(key_table_path('task_within_benchmark_similarity'))}`",
        f"- `{md_path(key_table_path('task_cross_benchmark_similarity'))}`",
        "",
        report_image("task_level/task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_level/task_best_representatives.png", "Best representative task per benchmark"),
        "",
        report_image("task_level/task_similarity_benchmark_pair_heatmap.png", "Task similarity across benchmark pairs"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict reliable tasks:",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier", "task_score"], 12),
        "",
        "Most representative tasks:",
        *markdown_table(representative_top, ["benchmark", "task_id", "useful_representativeness_score", "representativeness_score", "difficulty_tier", "task_score"], 12),
        "",
        "Benchmarks with strongest within-benchmark task similarity:",
        *markdown_table(task_similarity, ["benchmark", "n_reliable_tasks", "median_abs_task_similarity_within_benchmark"], 10),
        "",
        "**Insight and findings:** Task predictability and useful representativeness are different objectives. Representative tasks are the base set for predicting benchmark aggregates; hard-to-predict and difficult tasks are additional stress tests for broad coverage.",
        "",
        f"Paper-facing read: the hardest-to-predict task examples begin with {story_hard_tasks}. The most useful representative task examples begin with {story_representative_tasks}. That split is the main reason HaborMix should not be selected from one scalar alone: a task can be representative without being unique, and a unique task can be too idiosyncratic to stand in for its benchmark.",
        "",
        "## Study 6: Terminus Harnessing Effects",
        "",
        "**Method:** Terminus is treated as the fair baseline across models. For every model with both `terminus-2` and another agent row, I compute paired benchmark-relative score deltas while holding the model fixed.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_agent_lift_vs_terminus'))}`",
        f"- `{md_path(key_table_path('terminus_delta_by_model'))}`",
        f"- `{md_path(BENCHMARK_INTERMEDIATE_STUDY_DIR / 'benchmark_agent_lift_by_benchmark.csv')}`",
        "",
        report_image("benchmark_level/benchmark_agent_lift_heatmap.png", "Agent lift vs terminus by benchmark"),
        "",
        report_image("benchmark_level/terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        *markdown_table(terminus_by_model, ["model", "agent", "mean_delta_vs_terminus", "win_rate_vs_terminus"], 12),
        "",
        "**Insight and findings:** Paired deltas are the best current evidence for whether an agent harness improves over Terminus. The deltas vary by model and benchmark, so claims should avoid saying one harness universally dominates.",
        "",
        "## Study 7: HaborMix Selection",
        "",
        "**Method:** Candidate tasks must be reliable and bounded. The final HaborMix selection targets a compact 100-200 task set, currently 160 tasks. It first includes a small base set of useful representative tasks per benchmark, then fills the remaining slots with a diversity-aware ranking over difficult, frontier-with-variance, unique/unpredictable, and high-composite tasks. The composite score combines useful representativeness, difficulty, unique/unpredictable signal, and cross-agent/model discrimination; it no longer excludes frontier or saturated items by construction. The broader scored pool is retained under intermediate studies for auditability.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('harbormix_selected_tasks'))}`",
        f"- `{md_path(key_table_path('harbormix_selection_by_benchmark'))}`",
        f"- `{md_path(TASK_INTERMEDIATE_STUDY_DIR / 'harbormix_scored_task_pool.csv')}`",
        f"- `{md_path(TASK_INTERMEDIATE_STUDY_DIR / 'task_frontier_or_saturated_watchlist.csv')}`",
        "",
        report_image("harbormix/harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        report_image("task_level/task_reliable_difficulty_composition.png", "Reliable bounded task difficulty composition"),
        "",
        report_image("task_level/task_reliable_difficulty_composition_percent.png", "Reliable bounded task difficulty composition by percentage"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score", "mean_representative_signal", "mean_unique_unpredictable_signal", "mean_difficulty_signal"], 14),
        "",
        f"- Selected {len(selected_tasks)} final HaborMix tasks from the broader scored candidate pool.",
        "",
        "**Insight and findings:** HaborMix selection is quantitative and auditable: representative tasks anchor the minimal benchmark-prediction base, while difficult and unique/unpredictable tasks add breadth.",
        "",
        f"Paper-facing read: the final {len(selected_tasks)}-task set is intentionally not just a hard-task list. Its difficulty composition is {selected_tier_summary}. The base representative set keeps each included benchmark anchored to its aggregate behavior, while the diversity-aware fill adds difficult, frontier, and uniquely informative items.",
        "",
        "## Study 8: Task Aggregate vs Benchmark-Level Score Alignment",
        "",
        "**Method:** For each benchmark, I average benchmark-relative task scores and correlate that aggregate with the benchmark-level benchmark-relative score across agent+model rows. This is intentionally diagnostic rather than a hard gate: the new benchmark score is already the task aggregate, so this table mainly identifies benchmarks where reliable bounded tasks alone do or do not track the full task-derived benchmark aggregate.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('task_to_benchmark_alignment'))}`",
        "",
        report_image("task_level/task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation", "alignment_quality"], 12),
        "",
        "**Insight and findings:** Strong alignment means the reliable bounded subset is a good proxy for the task-derived benchmark score. Weak alignment is not used to remove benchmarks automatically; it flags cases for manual benchmark/task inspection.",
        "",
        "## Cross-Study Story",
        "",
        "The emerging story is that benchmark diversity matters more than a single aggregate leaderboard. Coverage filtering removes sparse columns from the main benchmark-level claims, and the imputation diagnostic makes the same point from the preprocessing side: the data are dense only after filling, and the selected fill is conservative because held-out validation did not justify stronger SVD structure by MAE.",
        "",
        "Within the retained benchmarks, model identity is usually more explanatory than agent identity, but the per-benchmark partial-R2 view prevents overstatement: some benchmark slices are much more sensitive to harness choice than the overall decomposition suggests. That is why the report keeps descriptive `agent+model` leaderboards for browsing, but uses paired Terminus deltas when making harness claims.",
        "",
        f"The BenchPress-style predictability layer identifies a preservation/compression axis. Benchmarks such as {story_unique_benchmarks} are hard to reconstruct and therefore carry distinctive signal. Benchmarks such as {story_predictable_benchmarks} are easier to reconstruct and can be grouped more aggressively. The clustered heatmaps and clustered mini-leaderboards give the visual version of the same argument.",
        "",
        "The task layer answers a different selection problem. Representative tasks are useful as small proxies for benchmark aggregates; unpredictable and difficult tasks are useful as stress tests. HaborMix combines those roles by taking representative base tasks first, then filling with difficult, unique, and discriminative tasks until the final compact set reaches the target size range. That is the clearest story for why HaborMix is not merely a random subset, not merely a hard subset, and not merely a redundant set of benchmark prototypes.",
        "",
        "## Artifact Index",
        "",
        "All key analysis tables:",
        *[f"- `{md_path(KEY_TABLE_DIR / name)}`" for name in key_tables],
        "",
        "All key analysis figures:",
        *[f"- `{md_path(KEY_FIGURE_DIR / name)}`" for name in key_figures],
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'per_benchmark')}/` ({per_benchmark_leaderboard_count} per-benchmark mini-leaderboard files, listed by directory rather than expanded here)",
        "",
        "## Not Completed Yet",
        "",
        "- Trial reliability, pass@k, efficiency curves, token/tool cost analysis, and trajectory failure taxonomy still require per-trial run records.",
        "- Full IRT/DIF still requires repeated binary/calibrated task outcomes or enough dense task observations to fit stable item-response models.",
        "- Provider scaling analysis still requires external model metadata such as provider family, parameter scale, release date, and inference budget.",
        "",
    ]
    (KEY_REPORT_DIR / "analysis_story.md").write_text("\n".join(report_lines))

    findings_lines = [
        "# Key Findings for Key Analysis Drafting",
        "",
        f"0. The processed benchmark matrix is task-first and uses `{best_task_imputer}` task filling, not direct benchmark imputation.",
        "",
        "Benchmark scores are simple means over the filled task matrix. The imputation reliability check compares candidate task fillers on held-out observed cells; SVD has lower RMSE here but higher MAE, so the selected fill is conservative rather than low-rank.",
        "",
        *markdown_table(task_imputation_cv, ["method", "rank", "holdout_cells", "rmse", "mae"], 5),
        "",
        f"1. Use {len(included_benchmarks)} coverage-filtered benchmarks for benchmark-level claims; keep sparse benchmarks in appendix/provisional analysis.",
        "",
        "The filtering table is now evidence-based on the task-first pipeline: benchmark scores come from filled-task aggregates, while the missingness columns describe how much original task evidence supported each aggregate before filling.",
        "",
        report_image("benchmark_level/benchmark_uniqueness_vs_coverage.png", "Benchmark predictability ranking"),
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_key_analysis", "observed_count", "task_cell_missing_fraction"], 8),
        "",
        "2. Model identity is the larger overall factor, but the model-vs-agent balance varies by benchmark; use the per-benchmark role plot for qualified claims.",
        "",
        "This is the clean answer to the agent-vs-model question: make the broad statement from the overall fixed-effect decomposition, then qualify it with per-benchmark partial R2 rather than collapsing everything into a single agent+model row label.",
        "",
        report_image("benchmark_level/benchmark_model_vs_agent_role.png", "Per-benchmark model vs agent explanatory power"),
        "",
        *markdown_table(role_gap, ["benchmark", _model_col, _agent_col, "dominant_dimension"], 8),
        "",
        "3. Separate model and agent dimensions. The useful agent evidence is paired lift over `terminus-2` for the same model, not an unqualified agent+model leaderboard.",
        "",
        "The Terminus table should be read as a harnessing-effect estimate: the paired comparison holds model fixed where the same model appears under Terminus and another agent.",
        "",
        report_image("benchmark_level/terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        "4. BenchPress-style predictability applies here: redundant benchmarks can be compressed; least-predictable benchmarks should be preserved for behavioral breadth.",
        "",
        "The benchmark-predictability result is deliberately separate from clustering: regression asks whether other benchmarks reconstruct a target, while the heatmap shows score-profile similarity. Use both when deciding whether two benchmarks are redundant.",
        "",
        report_image("benchmark_level/benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 8),
        "",
        "5. Task predictability and task representativeness are distinct: hard-to-predict tasks are stress tests, while representative tasks are compact proxies for a benchmark.",
        "",
        "The representative-task score now uses leave-one-out aggregate correlation times task variance, so tasks that are merely typical but non-discriminative are less likely to dominate the selected base set.",
        "",
        report_image("task_level/task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_level/task_best_representatives.png", "Best representative task per benchmark"),
        "",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier"], 8),
        "",
        *markdown_table(representative_top, ["benchmark", "task_id", "useful_representativeness_score", "difficulty_tier"], 8),
        "",
        f"6. The current HaborMix final set contains {len(selected_tasks)} diversified tasks.",
        "",
        "The HaborMix scorer is no longer centered on moderate difficulty. It first takes useful representative base tasks, then fills to a compact target size with difficult, frontier-with-variance, unique/unpredictable, and high-composite tasks.",
        "",
        report_image("harbormix/harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score"], 10),
        "",
        "7. Task-to-benchmark alignment should be used as a sanity check before interpreting benchmark-level scores from task-level tables.",
        "",
        "This table is diagnostic rather than a gate. Weak alignment means the reliable bounded subset may not proxy the full task-derived aggregate well; it does not automatically remove the benchmark from the benchmark-level analysis.",
        "",
        report_image("task_level/task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation", "alignment_quality"], 8),
        "",
        "Primary reference file: `output/key_analyses/reports/analysis_story.md`.",
    ]
    (KEY_REPORT_DIR / "key_findings.md").write_text("\n".join(findings_lines))
